
package ua.silentium;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrderServiceSoap", targetNamespace = "http://silentium.ua", wsdlLocation = "http://localhost:9697/SoapService/services/OrderServicePort?wsdl")
public class OrderServiceSoap
    extends Service
{

    private final static URL ORDERSERVICESOAP_WSDL_LOCATION;
    private final static WebServiceException ORDERSERVICESOAP_EXCEPTION;
    private final static QName ORDERSERVICESOAP_QNAME = new QName("http://silentium.ua", "OrderServiceSoap");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9697/SoapService/services/OrderServicePort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDERSERVICESOAP_WSDL_LOCATION = url;
        ORDERSERVICESOAP_EXCEPTION = e;
    }

    public OrderServiceSoap() {
        super(__getWsdlLocation(), ORDERSERVICESOAP_QNAME);
    }

    public OrderServiceSoap(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERSERVICESOAP_QNAME, features);
    }

    public OrderServiceSoap(URL wsdlLocation) {
        super(wsdlLocation, ORDERSERVICESOAP_QNAME);
    }

    public OrderServiceSoap(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDERSERVICESOAP_QNAME, features);
    }

    public OrderServiceSoap(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderServiceSoap(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrderWebServiceSEI
     */
    @WebEndpoint(name = "OrderServicePort")
    public OrderWebServiceSEI getOrderServicePort() {
        return super.getPort(new QName("http://silentium.ua", "OrderServicePort"), OrderWebServiceSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderWebServiceSEI
     */
    @WebEndpoint(name = "OrderServicePort")
    public OrderWebServiceSEI getOrderServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://silentium.ua", "OrderServicePort"), OrderWebServiceSEI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERSERVICESOAP_EXCEPTION!= null) {
            throw ORDERSERVICESOAP_EXCEPTION;
        }
        return ORDERSERVICESOAP_WSDL_LOCATION;
    }

}
