
package ua.silentium;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TourService", targetNamespace = "http://silentium.ua", wsdlLocation = "http://localhost:9697/SoapService/services/TourServicePort?wsdl")
public class TourService
    extends Service
{

    private final static URL TOURSERVICE_WSDL_LOCATION;
    private final static WebServiceException TOURSERVICE_EXCEPTION;
    private final static QName TOURSERVICE_QNAME = new QName("http://silentium.ua", "TourService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9697/SoapService/services/TourServicePort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TOURSERVICE_WSDL_LOCATION = url;
        TOURSERVICE_EXCEPTION = e;
    }

    public TourService() {
        super(__getWsdlLocation(), TOURSERVICE_QNAME);
    }

    public TourService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TOURSERVICE_QNAME, features);
    }

    public TourService(URL wsdlLocation) {
        super(wsdlLocation, TOURSERVICE_QNAME);
    }

    public TourService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TOURSERVICE_QNAME, features);
    }

    public TourService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TourService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TourWebServiceSEI
     */
    @WebEndpoint(name = "TourServicePort")
    public TourWebServiceSEI getTourServicePort() {
        return super.getPort(new QName("http://silentium.ua", "TourServicePort"), TourWebServiceSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TourWebServiceSEI
     */
    @WebEndpoint(name = "TourServicePort")
    public TourWebServiceSEI getTourServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://silentium.ua", "TourServicePort"), TourWebServiceSEI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TOURSERVICE_EXCEPTION!= null) {
            throw TOURSERVICE_EXCEPTION;
        }
        return TOURSERVICE_WSDL_LOCATION;
    }

}
