
package ua.silentium;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ua.silentium.entity.vouchers.Voucher;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VoucherWebServiceSEI", targetNamespace = "http://silentium.ua")
@XmlSeeAlso({
    ua.silentium.ObjectFactory.class,
    ua.silentium.entity.ObjectFactory.class,
    ua.silentium.entity.vouchers.ObjectFactory.class
})
public interface VoucherWebServiceSEI {


    /**
     * 
     * @param idVoucher
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteVoucher", targetNamespace = "http://silentium.ua", className = "ua.silentium.DeleteVoucher")
    @ResponseWrapper(localName = "deleteVoucherResponse", targetNamespace = "http://silentium.ua", className = "ua.silentium.DeleteVoucherResponse")
    public boolean deleteVoucher(
        @WebParam(name = "idVoucher", targetNamespace = "")
        int idVoucher);

    /**
     * 
     * @param voucher
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateVoucher", targetNamespace = "http://silentium.ua", className = "ua.silentium.UpdateVoucher")
    @ResponseWrapper(localName = "updateVoucherResponse", targetNamespace = "http://silentium.ua", className = "ua.silentium.UpdateVoucherResponse")
    public boolean updateVoucher(
        @WebParam(name = "voucher", targetNamespace = "")
        Voucher voucher);

    /**
     * 
     * @param voucher
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addVoucher", targetNamespace = "http://silentium.ua", className = "ua.silentium.AddVoucher")
    @ResponseWrapper(localName = "addVoucherResponse", targetNamespace = "http://silentium.ua", className = "ua.silentium.AddVoucherResponse")
    public boolean addVoucher(
        @WebParam(name = "voucher", targetNamespace = "")
        Voucher voucher);

    /**
     * 
     * @return
     *     returns java.util.List<ua.silentium.entity.vouchers.Voucher>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllVouchers", targetNamespace = "http://silentium.ua", className = "ua.silentium.FindAllVouchers")
    @ResponseWrapper(localName = "findAllVouchersResponse", targetNamespace = "http://silentium.ua", className = "ua.silentium.FindAllVouchersResponse")
    public List<Voucher> findAllVouchers();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllStatusVoucher", targetNamespace = "http://silentium.ua", className = "ua.silentium.FindAllStatusVoucher")
    @ResponseWrapper(localName = "findAllStatusVoucherResponse", targetNamespace = "http://silentium.ua", className = "ua.silentium.FindAllStatusVoucherResponse")
    public List<String> findAllStatusVoucher();

    /**
     * 
     * @param idPerson
     * @return
     *     returns java.util.List<ua.silentium.entity.vouchers.Voucher>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllVouchersbyPerson", targetNamespace = "http://silentium.ua", className = "ua.silentium.FindAllVouchersbyPerson")
    @ResponseWrapper(localName = "findAllVouchersbyPersonResponse", targetNamespace = "http://silentium.ua", className = "ua.silentium.FindAllVouchersbyPersonResponse")
    public List<Voucher> findAllVouchersbyPerson(
        @WebParam(name = "idPerson", targetNamespace = "")
        int idPerson);

    /**
     * 
     * @param idVoucher
     * @return
     *     returns ua.silentium.entity.vouchers.Voucher
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVoucher", targetNamespace = "http://silentium.ua", className = "ua.silentium.GetVoucher")
    @ResponseWrapper(localName = "getVoucherResponse", targetNamespace = "http://silentium.ua", className = "ua.silentium.GetVoucherResponse")
    public Voucher getVoucher(
        @WebParam(name = "idVoucher", targetNamespace = "")
        int idVoucher);

}
