//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.09 at 03:40:04 AM EET 
//

package ua.silentium.entity.vouchers;

import java.sql.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import ua.silentium.entity.Entity;

/**
 * <p>
 * Java class for Person complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Person">
 *   &lt;complexContent>
 *     &lt;extension base="{http://silentium.ua/entity}Entity">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="surname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="patronymic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="email" type="{http://silentium.ua/entity/vouchers}Email"/>
 *         &lt;element name="password" type="{http://silentium.ua/entity/vouchers}string" />
 *         &lt;element name="tel_num" type="{http://silentium.ua/entity/vouchers}Tel_num"/>
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="birth_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="document" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="role" type="{http://silentium.ua/entity/vouchers}Role"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Person", propOrder = { "name", "surname", "patronymic", "email", "password", "telNum", "address",
	"birthDate", "document", "role" })
public class Person extends Entity {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String surname;
    protected String patronymic;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    protected String password;
    @XmlElement(name = "tel_num")
    protected String telNum;
    protected String address;
    @XmlElement(name = "birth_date")
    @XmlSchemaType(name = "dateTime")
    protected Date birthDate;
    protected String document;
    @XmlElement(name = "Role", required = true)
    protected Role role;

    public Person() {
    }

    public Person(String name, String surname, String email, String password) {
	this.name = name;
	this.surname = surname;
	this.email = email;
	this.password = password;

	// TODO Auto-generated constructor stub
    }

    public Person(String name, String surname, String email, String password, String role) {
	this.name = name;
	this.surname = surname;
	this.email = email;
	this.password = password;
	this.role = new Role(role);

	// TODO Auto-generated constructor stub
    }
    
    public Person(int person_id) {
	this.id = person_id;
    
    }
    public Person(int id, String name, String surname, String email, String password, String role) {
	// TODO Auto-generated constructor stub
	this.id = id;
	this.name = name;
	this.surname = surname;
	this.email = email;
	this.password = password;
	this.role = new Role(role);
    }

    public boolean updatePerson(Person person) {
	if (person == null) {
	    return false;
	}
	this.id = person.id;
	this.name = person.name;
	this.surname = person.surname;
	this.patronymic = person.patronymic;
	this.email = person.email;
	this.password = person.password;
	this.telNum = person.telNum;
	this.address = person.address;
	this.birthDate = person.birthDate;
	this.document = person.document;
	this.role = person.role;
	return true;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName() {
	return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setName(String value) {
	this.name = value;
    }

    /**
     * Gets the value of the surname property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSurname() {
	return surname;
    }

    /**
     * Sets the value of the surname property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSurname(String value) {
	this.surname = value;
    }

    /**
     * Gets the value of the patronymic property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPatronymic() {
	return patronymic;
    }

    /**
     * Sets the value of the patronymic property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPatronymic(String value) {
	this.patronymic = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEmail() {
	return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setEmail(String value) {
	this.email = value;
    }

    /**
     * Gets the value of the telNum property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPassword() {
	return password;
    }

    public void setPassword(String value) {
	this.password = value;
    }

    public String getTelNum() {
	return telNum;
    }

    /**
     * Sets the value of the telNum property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTelNum(String value) {
	this.telNum = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAddress() {
	return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setAddress(String value) {
	this.address = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public Date getBirthDate() {
	return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setBirthDate(Date value) {
	this.birthDate = value;
    }

    /**
     * Gets the value of the document property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDocument() {
	return document;
    }

    /**
     * Sets the value of the document property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDocument(String value) {
	this.document = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return possible object is {@link Role }
     * 
     */
    public Role getRole() {
	return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value allowed object is {@link Role }
     * 
     */
    public void setRole(Role value) {
	this.role = value;
    }

    @Override
    public String toString() {
	StringBuilder builder = new StringBuilder();
	builder.append("Person(name=");
	builder.append(name);
	builder.append(", surname=");
	builder.append(surname);
	builder.append(", patronymic=");
	builder.append(patronymic);
	builder.append(", email=");
	builder.append(email);
	builder.append(", telNum=");
	builder.append(telNum);
	builder.append(", address=");
	builder.append(address);
	builder.append(", birthDate=");
	builder.append(birthDate);
	builder.append(", document=");
	builder.append(document);
	builder.append(", role=");
	builder.append(role);
	builder.append(")");
	return builder.toString();
    }

}
