//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.09 at 03:40:04 AM EET 
//


package ua.silentium.entity.vouchers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import ua.silentium.entity.Entity;


/**
 * <p>Java class for Status_voucher.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Status_voucher">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Booked"/>
 *     &lt;enumeration value="Waiting for"/>
 *     &lt;enumeration value="Confirmed"/>
 *     &lt;enumeration value="In the process"/>
 *     &lt;enumeration value="Completed"/>
 *     &lt;enumeration value="Annulled"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatusVoucher", propOrder = {
    "name",
})
public class StatusVoucher extends Entity {

    
    @XmlElement(name = "status_voucher_name", required = true)
    protected String name;
    
    public StatusVoucher() {
    }
    public StatusVoucher(int idStatusVoucher, String name) {
	this.id = idStatusVoucher;
	this.name = name;
    }
    
    public StatusVoucher(String statusVoucher) {
	this.name = statusVoucher;
	// TODO Auto-generated constructor stub
    }
    public String getStatusVoucherName() {
        return name;
    }

  
    public void setStatusVoucherName(String value) {
        this.name = value;
    }


}
