//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.09 at 03:40:04 AM EET 
//

package ua.silentium.entity.vouchers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import ua.silentium.entity.Entity;

/**
 * <p>Java class for Status_order.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Status_order">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Waiting for"/>
 *     &lt;enumeration value="Confirmed"/>
 *     &lt;enumeration value="Annulled"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatusOrder", propOrder = {
    "name",
})
public class StatusOrder extends Entity {

    
    @XmlElement(name = "status_order_name", required = true)
    protected String name;
    
    public StatusOrder() {
    }
    public StatusOrder(String name) {
	this.name = name;
    }
    public StatusOrder(int idStatusOrder, String name) {
	this.id = idStatusOrder;
	this.name = name;
    }
    
    public String getStatusOrderName() {
        return name;
    }

  
    public void setStatusOrderName(String value) {
        this.name = value;
    }


}
