//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.09 at 03:40:04 AM EET 
//


package ua.silentium.entity.vouchers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import ua.silentium.entity.Entity;


/**
 * <p>Java class for Type_transport.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Type_transport">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Bus"/>
 *     &lt;enumeration value="Airpale"/>
 *     &lt;enumeration value="Cruise ship"/>
 *     &lt;enumeration value="Foot"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type_transport", propOrder = {
    "name",
})
public class TypeTransport extends Entity {

    @XmlElement(name = "type_transport_name", required = true)
    protected String name;
    
    public TypeTransport() {
    }
    
    public TypeTransport(int idTypeTransport, String name) {
	this.id = idTypeTransport;
	this.name = name;
    }
    public TypeTransport(String name) {
	this.name = name;
    }
    
    
    public String getTypeTransportName() {
        return name;
    }

    /**
     * Sets the value of the tourName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeTransportName(String value) {
        this.name = value;
    }
}
