
package ua.silentium.entity.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.4.4
 * Wed Dec 22 03:46:15 EET 2021
 * Generated source version: 3.4.4
 */

@XmlRootElement(name = "addTourDate", namespace = "http://silentium.ua")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addTourDate", namespace = "http://silentium.ua")

public class AddTourDate {

    @XmlElement(name = "tourdate")
    private ua.silentium.entity.vouchers.TourDate tourdate;

    public ua.silentium.entity.vouchers.TourDate getTourdate() {
        return this.tourdate;
    }

    public void setTourdate(ua.silentium.entity.vouchers.TourDate newTourdate)  {
        this.tourdate = newTourdate;
    }

}

