
package ua.silentium.entity.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.4.4
 * Wed Dec 22 03:46:55 EET 2021
 * Generated source version: 3.4.4
 */

@XmlRootElement(name = "checkPerson", namespace = "http://silentium.ua")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "checkPerson", namespace = "http://silentium.ua", propOrder = {"email", "password"})

public class CheckPerson {

    @XmlElement(name = "email")
    private java.lang.String email;
    @XmlElement(name = "password")
    private java.lang.String password;

    public java.lang.String getEmail() {
        return this.email;
    }

    public void setEmail(java.lang.String newEmail)  {
        this.email = newEmail;
    }

    public java.lang.String getPassword() {
        return this.password;
    }

    public void setPassword(java.lang.String newPassword)  {
        this.password = newPassword;
    }

}

