
package ua.silentium.entity.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.4.4
 * Wed Dec 22 03:47:25 EET 2021
 * Generated source version: 3.4.4
 */

@XmlRootElement(name = "deleteOrder", namespace = "http://silentium.ua")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deleteOrder", namespace = "http://silentium.ua")

public class DeleteOrder {

    @XmlElement(name = "idOrder")
    private int idOrder;

    public int getIdOrder() {
        return this.idOrder;
    }

    public void setIdOrder(int newIdOrder)  {
        this.idOrder = newIdOrder;
    }

}

