
package ua.silentium.entity.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.4.4
 * Wed Dec 22 03:46:55 EET 2021
 * Generated source version: 3.4.4
 */

@XmlRootElement(name = "deletePerson", namespace = "http://silentium.ua")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deletePerson", namespace = "http://silentium.ua")

public class DeletePerson {

    @XmlElement(name = "idPerson")
    private int idPerson;

    public int getIdPerson() {
        return this.idPerson;
    }

    public void setIdPerson(int newIdPerson)  {
        this.idPerson = newIdPerson;
    }

}

