
package ua.silentium.entity.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.4.4
 * Wed Dec 22 03:47:48 EET 2021
 * Generated source version: 3.4.4
 */

@XmlRootElement(name = "deleteVoucher", namespace = "http://silentium.ua")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deleteVoucher", namespace = "http://silentium.ua")

public class DeleteVoucher {

    @XmlElement(name = "idVoucher")
    private int idVoucher;

    public int getIdVoucher() {
        return this.idVoucher;
    }

    public void setIdVoucher(int newIdVoucher)  {
        this.idVoucher = newIdVoucher;
    }

}

