
package ua.silentium.entity.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.4.4
 * Wed Dec 22 03:47:48 EET 2021
 * Generated source version: 3.4.4
 */

@XmlRootElement(name = "updateVoucher", namespace = "http://silentium.ua")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateVoucher", namespace = "http://silentium.ua")

public class UpdateVoucher {

    @XmlElement(name = "voucher")
    private ua.silentium.entity.vouchers.Voucher voucher;

    public ua.silentium.entity.vouchers.Voucher getVoucher() {
        return this.voucher;
    }

    public void setVoucher(ua.silentium.entity.vouchers.Voucher newVoucher)  {
        this.voucher = newVoucher;
    }

}

