
package ua.silentium.entity.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.4.4
 * Wed Dec 22 03:47:25 EET 2021
 * Generated source version: 3.4.4
 */

@XmlRootElement(name = "updateOrder", namespace = "http://silentium.ua")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateOrder", namespace = "http://silentium.ua")

public class UpdateOrder {

    @XmlElement(name = "order")
    private ua.silentium.entity.vouchers.Order order;

    public ua.silentium.entity.vouchers.Order getOrder() {
        return this.order;
    }

    public void setOrder(ua.silentium.entity.vouchers.Order newOrder)  {
        this.order = newOrder;
    }

}

