
package ua.silentium.entity.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.4.4
 * Wed Dec 22 03:46:55 EET 2021
 * Generated source version: 3.4.4
 */

@XmlRootElement(name = "updatePerson", namespace = "http://silentium.ua")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updatePerson", namespace = "http://silentium.ua")

public class UpdatePerson {

    @XmlElement(name = "person")
    private ua.silentium.entity.vouchers.Person person;

    public ua.silentium.entity.vouchers.Person getPerson() {
        return this.person;
    }

    public void setPerson(ua.silentium.entity.vouchers.Person newPerson)  {
        this.person = newPerson;
    }

}

